### ISSUE TITLE
[proposal] TFT_eSPI support

### ISSUE THREAD

**Issue by oxyii** [yoprogramo/QRcodeDisplay#1]
[TFT_eSPI](https://github.com/Bodmer/TFT_eSPI) is much faster than Adafruit. It will be nice if support it too. Your `QRcode_ST7735` modified for `TFT_eSPI` is [here](https://gist.github.com/oxyii/76265cfef0bde9bc6ce80b122f5e5514). Tested on my `TTGO TS v1.0` 1,44'' 128x128 ST7735.

You can publish it if you'd like or just close this issue

**Comment by yoprogramo** [comment]
Good proposal,

I'll test with my hardware and then I'll decide what to do.

Thank you

**Comment by yoprogramo** [comment]
Hello again, I'm trying to make work my ESP32 + 128x128 ST7735 hardware with TFT_eSPI but my screen are displaced. Maybe I'm not adjusting the user_setup properly. Can you tell me what is the setup you have tested...?

**Comment by oxyii** [comment]
This is my config for TFT_eSPI https://github.com/Xinyuan-LilyGO/LilyGo_Txx/blob/master/User_Setups/T10_V14.h

**Comment by oxyii** [comment]
Only one `include` must be in [User_Setup_Select.h](https://github.com/Bodmer/TFT_eSPI/blob/master/User_Setup_Select.h). So you can create your own `.h` file (based on my, for example) and `include` it instead of `<User_Setup.h>`. Must work i think

**Comment by yoprogramo** [comment]
I have tested using platformio and defining the configuration in platformio.ini file. In my case:

`
[env:esp32-espi]
platform = espressif32
board = esp32dev
framework = arduino
build_flags =
    -DUSER_SETUP_LOADED
    -DST7735_DRIVER
    -DST7735_GREENTAB3
    -DTFT_WIDTH=128
    -DTFT_HEIGHT=128
    -DTFT_MISO=26
    -DTFT_MOSI=23
    -DTFT_SCLK=18
    -DTFT_CS=5
    -DTFT_DC=26
lib_deps = 
    yoprogramo/QRcodeDisplay @ ^1.0.0
    yoprogramo/QRcode_eSPI @ ^1.0.0
    bodmer/TFT_eSPI
monitor_speed = 115200
upload_speed = 115200
upload_port = /dev/ttyUSB*
`

So, it works, let publish the classes in https://github.com/yoprogramo/QRcode_eSPI. Feel free to add/remove whatever you consider.

**Comment by oxyii** [comment]
`qrcode.create` time approximately on my hardware:
- without transaction - 129 200 micros
- with transaction - 69 700 micros

I think we can override `qrcode.create` something like this:
```cpp
// define `create` in .h

void QRcode_eSPI::create(String message) {
  display->startWrite();
  QRcodeDisplay::create(message);
  display->endWrite();
}
```

Sorry i don't create PR... it is not very convenient for me now

**Comment by oxyii** [comment]
I'm not sure about checking `SUPPORT_TRANSACTIONS` definition

**Comment by oxyii** [comment]
TFT_eSPI [checks](https://github.com/Bodmer/TFT_eSPI/blob/58f457ba9703613bfcd70b411d66bbbc948fa815/TFT_eSPI.cpp#L60) this definition... but i see nothing performance changes if `SUPPORT_TRANSACTIONS` defined or not in my config for TFT_eSPI. Looks like it is safe to implement my proposal

**Comment by yoprogramo** [comment]
OK,

Let me include the modification and test it..

**Comment by yoprogramo** [comment]
Done, QRcode_eSPI 1.0.1 already have your modifications.

**Comment by oxyii** [comment]
@yoprogramo  Great job! Thank you very much! I'll use it right now )
