### ISSUE TITLE
Change mode

### ISSUE THREAD

**Issue by slavendam** [yoprogramo/QRcodeDisplay#10]
Hi, 
is it possible to change mode from byte to alphanumeric?

I succeed to generate frame.c file, but I don't see parameter to change mode.

Thanks!

**Comment by yoprogramo** [comment]
Hello, 

We only support one mode that allows you to encode any string. We do not have plans to support other more limited modes for the moment. If you find some other libraries that implements in a efficient way, please let me know to see if it is possible to integrated in the library.

**Comment by slavendam** [comment]
Thanks for info!

I succeed to get QR code with this library: https://github.com/ricmoo/QRCode
It has option to automtically check if text is number, alphanumeric or byte. 

And here are libraries to display that QR code: 
https://github.com/yoprogramo/QRcodeDisplay
https://github.com/yoprogramo/QRcode_ST7789
