### ISSUE TITLE
Generated frame.c files

### ISSUE THREAD

**Issue by slavendam** [yoprogramo/QRcodeDisplay#11]
I've generated different frame.c files so you can add that to library. Files are for versions from 1 to 9.
It is not easy for everyone to set everything on Windows. I hope this will save some time :)

[qrduino-frame-files.zip](https://github.com/yoprogramo/QRcodeDisplay/files/10447634/qrduino-frame-files.zip)

**Comment by yoprogramo** [comment]
Thankyou for the contribution @slavendam I have generated a new version when you can compile to any QR version you like (from 1 to 10).
