### ISSUE TITLE
[QUESTION] increse string size

### ISSUE THREAD

**Issue by MateusDornelles** [yoprogramo/QRcodeDisplay#2]
Hi, how can I increase the maximum string size  ?  My string has 176 characters, the limit appears to be 154.

Thanks.

**Comment by yoprogramo** [comment]
Hello,

The only limit we have fixed is the 256 bytes on the buffer, but you have to take into account the size limitations and max number of modules that your screen can paint. We are using a matrix of 45x45 that allows from 154 to 370 characters depending on the ECC Level (we are using Level 7 ECC H) so you can only paint 154 characters.

You can tune the file frame.c to change the values used but you should regenerate the frames as well. You can do all the process with the command  dofbit in this repo: https://github.com/tz1/qrduino. Let me know if you make it.

**Comment by MateusDornelles** [comment]
Hi yoprogramo, it worked. 

Thank you for your time.

**Comment by yoprogramo** [comment]
Congrats! can you please send me the changes to frame.c you do? Just to see if I can integrate it.

Regards.

**Comment by yoprogramo** [comment]
Waiting for modified code to integrate, I close this issue

**Comment by MateusDornelles** [comment]
Hi yoprogramo, sorry for the delay. What i did was to clone the repository you passed (https://github.com/tz1/qrduino), then i used the program dofbit with the params 8 (version) and 1(ECC) to generate the new frame.c, I just replaced the contents of the old file with the output generated by dofbit.

[frame.txt](https://github.com/yoprogramo/QRcodeDisplay/files/8341660/frame.txt)

**Comment by tkjoko09** [comment]
Hi yoprogramo. can you help me to change the frame.c to accept Version 10? i think we need it now, I use ESP32 so it can hold more memory. BTW, i am a newbe so i cant generate it by my self. Thanks for your Attention.
