### ISSUE TITLE
Typo in ReadMe

### ISSUE THREAD

**Issue by CaseyJNova** [yoprogramo/QRcodeDisplay#4]
Just learning how to make an Issue and then perform a Pull Request for GitHub.

I see a couple of typos in the readMe and would like to submit an edit. Is this the right path?

**Comment by yoprogramo** [comment]
Yes, please, modify it and create a merge request.

**Comment by yoprogramo** [comment]
Hello @CaseyJScalf , finally will you send us the contribution or may I close the issue?
