### ISSUE TITLE
Codigo QR muy pequeño

### ISSUE THREAD

**Issue by migrassi** [yoprogramo/QRcodeDisplay#6]
Hola Jose Antonio. Estoy usando tu librería en un display TFT ST7789 de 240x240 px y funciona perfectamente. El inconveniente que tengo es que el código sale muy pequeño en la pantalla. Queda perfectamente centrado pero ocupa aproximadamente 1/3 del ancho y 1/3 del alto del display. Veo que otras personas han implementado el mismo display y el código generado cabe perfectamente en toda la pantalla. ¿Me puedes orientar para encontrar una solución al problema? Muchas gracias.

**Comment by yoprogramo** [comment]
Hola @migrassi ,

La verdad es que el tamaño se calcula para que ocupe lo máximo posible para que los puntos sean cuadrados, es decir, cada punto puede ocupar un pixel o 2x2 o 3x3 y así. Esta versión de la librería usa nivel 7 que son 45x45 puntos, si usamos puntos dobles serían 90x90, el ideal para tu pantalla es usar 5x5 px que daría un tamaño de 225x225 y que ocuparía toda la pantalla. 

Asegurate que inicializas con init(240,240), que te daría un multiplicador de 5. En la versión actual solo pinta los puntos 2x2, pero debería pintarlos de manera correcta distribuidos en la pantalla. Revisa el init y si persiste el problema mandame una foto de cómo te aparece y el código que utilizas para que pueda ver si es otra cosa.

**Comment by migrassi** [comment]
Gracias @yoprogramo por la rápida respuesta. No se si te refieres al init de la pantalla  que si estoy inicializando indicando el tamaño en píxeles (`display.init(240, 240, SPI_MODE2)` ) o al init del qrcode `qrcode.init()` En este último caso, no puedo inicializarlo con `qrcode.init(240,240)` ya que está prototipado sin parámetros en *qrcode_st7789.h*. Probé comentando esa línea y así el editor me sugiere dos parámetros *uint16_t*, pero si los pongo aparecen otros errores de compilación. Mi código de prueba completo es el siguiente:

```
#include <Arduino.h>
#include <Adafruit_GFX.h>    // Core graphics library
#include <Adafruit_ST7789.h> // Hardware-specific library for ST7789
#include <SPI.h>             // Arduino SPI library
#include <qrcode_st7789.h>

// ST7789 TFT module connections
#define TFT_RST 4 // Reset
#define TFT_CS -1 // define chip select pin 
#define TFT_DC 5  //  data/command pin
#define TFT_BL 15 //  BLK - backlight

Adafruit_ST7789 display = Adafruit_ST7789(TFT_CS, TFT_DC, TFT_RST);
QRcode_ST7789 qrcode(&display);

void setup(void)
{
  display.init(240, 240, SPI_MODE2); // Init ST7789 240x240
  pinMode(TFT_BL, OUTPUT);
  digitalWrite(TFT_BL, HIGH);
  // Initialize QRcode display 
  qrcode.init (();
  // create qrcode
  qrcode.create("Hola mundo");
}

void loop()
{
}
```
Un saludo desde Argentina

**Comment by yoprogramo** [comment]
Tienes razón, hay un bug que limita el multiplicador en ST7789, mira a ver si te puedes bajar el código que hay ahora en [master](https://github.com/yoprogramo/QRcode_ST7789) (si te funciona genero una nueva versión para todo el mundo)

**Comment by migrassi** [comment]
Descargué las versión que me sugeriste. El QR ocupa toda la pantalla ahora, pero los puntos en lugar de ser llenos, están separados entre si. Me sucedió lo mismo cuando cambié manualmente los números dentro de la librería. Adjunto una imagen.

![20220603_191722](https://user-images.githubusercontent.com/5194735/171962189-f055a65f-5e59-4c41-9309-52a5294bf2c5.jpg)

**Comment by yoprogramo** [comment]
Si, son puntos 2x2. Voy a ver si puedo hacer que sean solidos sin estropear
nada mas. Cuando suba la nueva versión te aviso.

**Comment by yoprogramo** [comment]
@migrassi prueba ahora con lo que hay en el repositorio y me dices

**Comment by migrassi** [comment]
Funciona perfectamente ahora. Excelente trabajo, @yoprogramo ! Adjunto imagen. Muchas gracias!
![20220604_112049](https://user-images.githubusercontent.com/5194735/172006906-9a1ea15f-0ef8-47bc-b4d9-cd08e3b73406.jpg)

**Comment by yoprogramo** [comment]
Perfecto, genero nueva versión y cierro esta incidencia.
