### ISSUE TITLE
Release 2.0.1 still has version "2.0.0" in the zip-file.

### ISSUE THREAD

**Issue by hhv** [yoprogramo/QRcodeDisplay#8]
I just downloaded the zip file for release 2.0.1, only to discover there's still a "2.0.0" in the library.json and library.properties files. So PlatformIO complains. In Git the version is "2.0.1" but not in the downloaded zip file. Also, PlatformIO is still on QRcodeDisplay@^2.0.0 and QRcodeOlead@^1.0.0 - that's why I downloaded the zip-files.

**Comment by yoprogramo** [comment]
I have changed the release in github, let me see if I can publish too in platformio and/or arduino libraries or replaced for another version number

**Comment by yoprogramo** [comment]
v2.0.2 available now, please try it and tell me if it works (Modified the QRcodeOled also).

**Comment by hhv** [comment]
Hi, I just upgraded to 2.0.2 using PlatformIO. Excellent, thanks for the quick fix!

**Comment by yoprogramo** [comment]
Thank you for the warning. Let's close the issue.
