### ISSUE TITLE
Example for I2C 1.3" OLED SH1106 display

### ISSUE THREAD

**Issue by lybce** [yoprogramo/QRcodeDisplay#9]
Hi, great job, but I cant find an example with SH1106 controller display
Can you provide it ?

Thanks

**Comment by yoprogramo** [comment]
Hello,

Try this:

https://github.com/yoprogramo/QRcodeOled/tree/master/examples/simplessh1106

**Comment by lybce** [comment]
Muchas gracias jose !!!!
Estuve renegando un buen rato hasta descubrir que el controlador era distinto !!

Saludos desde Argentina

Gabriel Locatelli
 [cid:21adf889-c72f-49de-8efa-5d4ecfcd9acb]
[cid:a461ad9b-01ef-4af7-816e-38c19381db15]​Jose Marmol 389, CABA ***@***.***,-58.4281222,17z/data=!3m1!4b1!4m5!3m4!1s0x95bcca5afff2c471:0x479667a24e785f73!8m2!3d-34.617767!4d-58.4259436>
[cid:923879c7-fcba-48dd-a825-2319fcda7fef] 11 6698-5913 [cid:1a381cef-d5e6-4e99-83f6-06bea7c740e5] +54 9 11 59829200<https://wa.me/+5491159829200>
________________________________
De: Jose Antonio Espinosa ***@***.***>
Enviado: jueves, 24 de noviembre de 2022 13:08
Para: yoprogramo/QRcodeDisplay ***@***.***>
Cc: GAL ***@***.***>; Author ***@***.***>
Asunto: Re: [yoprogramo/QRcodeDisplay] Example for I2C 1.3" OLED SH1106 display (Issue #9)


Hello,

Try this:

https://github.com/yoprogramo/QRcodeOled/tree/master/examples/simplessh1106

**Comment by yoprogramo** [comment]
De nada, espero que te sirva.

**Comment by lybce** [comment]
Perfecto !!

Consulta tecnica, pensando en posibles problemas como ser pixels muertos o desgaste, es posible cambiar la posicion horizontal del qr en pantalla ??

Desde ya muchas gracias Jose !!

Gabriel Locatelli
 [cid:5ee3de19-8dc2-4589-b3be-3632966022b9]
[cid:4417a1f1-1100-483a-8269-4d6dd8b155b8]​Jose Marmol 389, CABA ***@***.***,-58.4281222,17z/data=!3m1!4b1!4m5!3m4!1s0x95bcca5afff2c471:0x479667a24e785f73!8m2!3d-34.617767!4d-58.4259436>
[cid:3bce0564-5a0e-40ae-905c-371694703c18] 11 6698-5913 [cid:6b36a4ae-1c7f-42ec-94cc-2953460a4821] +54 9 11 59829200<https://wa.me/+5491159829200>
________________________________
De: Jose Antonio Espinosa ***@***.***>
Enviado: jueves, 24 de noviembre de 2022 17:14
Para: yoprogramo/QRcodeDisplay ***@***.***>
Cc: GAL ***@***.***>; Author ***@***.***>
Asunto: Re: [yoprogramo/QRcodeDisplay] Example for I2C 1.3" OLED SH1106 display (Issue #9)


De nada, espero que te sirva.

**Comment by lybce** [comment]
![OLED_1v3_QR](https://user-images.githubusercontent.com/62491212/203861168-f9b2566f-9fad-4a20-9ae5-fcf084ef74b0.jpeg)

**Comment by yoprogramo** [comment]
Hola de nuevo,

El QR se centra en la pantalla automáticamente, pero puedes llamar al init con otro tamaño (por ejemplo diciendo que es cuadrado y así te lo pinta más a la izquierda)... Es un truco, pero puede servirte combinado con la rotación del display para ponerlo a izquierda o derecha.

**Comment by lybce** [comment]
Voy a probar, gracias !!!El 24 nov. 2022 19:06, Jose Antonio Espinosa ***@***.***> escribió:

Hola de nuevo,

El QR se centra en la pantalla automáticamente, pero puedes llamar al init con otro tamaño (por ejemplo diciendo que es cuadrado y así te lo pinta más a la izquierda)... Es un truco, pero puede servirte combinado con la rotación del display para ponerlo a izquierda o derecha.
